#include"Menu.h"
/*
Реализирал съм системата на 5 нива:
0)Функцията Меnu-грижи се за прочита от конзалата и коректоността на необходимите команди
1)Класат Validation-ВАЛИДИРА получените,аргументи от Menu и чрез функциите вътре,които връщат стрингово съобщение за
резултата от извършената операцията в класовете 2),3) или 4),сигнализира на конзолата
2)Класът Система-грижи се за потребителите в системата-тяхното добяване,блокиране/разблокирване,премахване и преименуване
3)Класът Потребител-грижи се за постовете на всеки потребител,тяхното добавяне и премахване
4)Класът Пост,чиято работа е да визуализира,съответните постове в HTML файл
/////////////////
Възникне ли изключение по време на работа ,в main се прихваща и съобщава за него след което програмата приключва
Въпреки че някъде хвърлям грешка ралична от bad_alloc в този случай се работи само през конзолата
и може да възникне само тази грешка
*/

int main()
{
	std::cout << "The allowed commad are:\n"
		<< "1:<ACTOR-NAME> <add_moderator/add_users> <SUBJECT-NAME>  <AGE>\n"
		<< "2:<ACTOR-NAME> <remove_user> <SUBJECT-NAME>\n"
		<< "3:<ACTOR-NAME> <block/unblock> <SUBJECT-NAME>\n"
		<< "4:<ACTOR-NAME> <post> <[image]/[url]/[text]> <CONTENT/CONTENT AND DESCR/CONTENT/>\n"
		<< "5:<ACTOR-NAME> <remove_post> <ID>\n"
		<< "6:<ACTOR-NAME> <view_post><ID>\n"
		<< "7:<ACTOR-NAME> <view_all_posts><SUBJECT-NAME>\n"
		<< "8:<ACTOR-NAME> <rename> <NEW-NAME>\n"
		<< "9:<info>\n"
		<< "10:<quit>\n";
	try
	{
		Menu();
	}
	catch (const std::exception &e)
	{
		e.what();
	}
	return 0;
}